name: 'aks-cluster-bootstrap'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: testing
        run: "echo ${{ vars.myname }}"